language: node_js
node_js:
  - 0.12
sudo: required
script: node_modules/.bin/karma start ./karma.conf.js --single-run
before_script:
  - 'git config --global user.email "doradora56@gmail.com"'
  - 'git config --global user.name "Travis-CI"'
before_install:
  - export CHROME_BIN=chromium-browser
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
after_script:
  - bash ./deploy.sh
cache:
  directories:
    - node_modules
env:
  global:
    - secure: G1bUE3a7zN3Q46MdQbePeW1+CchaCKK9+XfN8LTV5G4v+9Hh5aORBUM/5+3AVoNPLINyXQunJgci5OWAYtTOT8IVX8TTYYQhu9boN6ts4HafAiSjrjjfNItH4cVDGwc0gzTOmq5Bgwl/eEmLoNNHw8Z1wpXw7nUM3kJQ8ZcGbBw5JhUUbyUVMucC4giAfuJZPpz1vhylGXZvLFL8z8Wk78zroQnl2Hg46j0CsopZDZLtvKher0tZi0qXBYZlJj27Ek7K34YZUzs+o797Me7BI9+F0WbbFHvOi8FXjw5yMOHtHr2FLRVDS+ROtUAhDPiHiPMrtE39Yii+VI0/RomZ/UM+XZNlMTqGUz4e4A192VbqpTR2srxnAG/0ICYClRcYaS+NGRcnyALfiz+s2FH6mCnwPDA1UBmYZ39qGp3IXj05LEtVdxf7i1fV6I4prW9h3KlCbFfKale6NsmHI8jJApRQqKko0GkRfC/6Np4nZ91NCoTQc9g9rQtRyHHBpJ8QIyGZlWmo/ZQuXprJxyYN11Z/kx9K3HbbirLnyKrtdlQgj8NmhT6tAY4vpb6+lwoTNToeWhResrNeZyyBNSJCpU34XPbnAb1a3LhSO+V8nAqYNuR20b3Y+cJZ2N/ekESjueIzCrptXkPRYBwa+C4Li13jw62G13NYoQHva8zz7zs=
